// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock_App.EntityFramework;

#nullable disable

namespace Stock_App.EntityFramework.Migrations
{
    [DbContext(typeof(StockAppDbContext))]
    partial class StockAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Stock_App.EntityFramework.DTOs.StockItemDto", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Ticker");

                    b.ToTable("StockItems");
                });
#pragma warning restore 612, 618
        }
    }
}
